FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS install
COPY package.json ./
RUN bun install

FROM base AS release
COPY --from=install /app/node_modules ./node_modules
COPY src/ ./src/

CMD ["bun", "src/main.ts"]
