upstream backend {
    server localhost:5000;
    # server 10.0.1.1:5000;
}

server {
    server_name api.mktsum.yxnliu.net;

    # block internal routes from outside world
    location /internal {
        return 403;
    }

    # only allow v1 public routes
    location /v1 {
        proxy_pass http://backend;        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    # block everything else
    location / {
        return 404;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.mktsum.yxnliu.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.mktsum.yxnliu.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = api.mktsum.yxnliu.net) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name api.mktsum.yxnliu.net;
    return 404;
}