/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as WatchlistTickerRouteImport } from './routes/watchlist/$ticker'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as ComponentsComponentNameRouteImport } from './routes/components/$componentName'
import { Route as BriefingsAllRouteImport } from './routes/briefings/all'
import { Route as BriefingsBriefingIdRouteImport } from './routes/briefings/$briefingId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistTickerRoute = WatchlistTickerRouteImport.update({
  id: '/watchlist/$ticker',
  path: '/watchlist/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentNameRoute = ComponentsComponentNameRouteImport.update({
  id: '/components/$componentName',
  path: '/components/$componentName',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsAllRoute = BriefingsAllRouteImport.update({
  id: '/briefings/all',
  path: '/briefings/all',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsBriefingIdRoute = BriefingsBriefingIdRouteImport.update({
  id: '/briefings/$briefingId',
  path: '/briefings/$briefingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/briefings/$briefingId': typeof BriefingsBriefingIdRoute
  '/briefings/all': typeof BriefingsAllRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watchlist/$ticker': typeof WatchlistTickerRoute
  '/components/': typeof ComponentsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/briefings/$briefingId': typeof BriefingsBriefingIdRoute
  '/briefings/all': typeof BriefingsAllRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watchlist/$ticker': typeof WatchlistTickerRoute
  '/components': typeof ComponentsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/briefings/$briefingId': typeof BriefingsBriefingIdRoute
  '/briefings/all': typeof BriefingsAllRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watchlist/$ticker': typeof WatchlistTickerRoute
  '/components/': typeof ComponentsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/briefings/$briefingId'
    | '/briefings/all'
    | '/components/$componentName'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watchlist/$ticker'
    | '/components/'
    | '/legal/'
    | '/watchlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/briefings/$briefingId'
    | '/briefings/all'
    | '/components/$componentName'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watchlist/$ticker'
    | '/components'
    | '/legal'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/briefings/$briefingId'
    | '/briefings/all'
    | '/components/$componentName'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watchlist/$ticker'
    | '/components/'
    | '/legal/'
    | '/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  BriefingsBriefingIdRoute: typeof BriefingsBriefingIdRoute
  BriefingsAllRoute: typeof BriefingsAllRoute
  ComponentsComponentNameRoute: typeof ComponentsComponentNameRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  WatchlistTickerRoute: typeof WatchlistTickerRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/$ticker': {
      id: '/watchlist/$ticker'
      path: '/watchlist/$ticker'
      fullPath: '/watchlist/$ticker'
      preLoaderRoute: typeof WatchlistTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentName': {
      id: '/components/$componentName'
      path: '/components/$componentName'
      fullPath: '/components/$componentName'
      preLoaderRoute: typeof ComponentsComponentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/all': {
      id: '/briefings/all'
      path: '/briefings/all'
      fullPath: '/briefings/all'
      preLoaderRoute: typeof BriefingsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/$briefingId': {
      id: '/briefings/$briefingId'
      path: '/briefings/$briefingId'
      fullPath: '/briefings/$briefingId'
      preLoaderRoute: typeof BriefingsBriefingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  BriefingsBriefingIdRoute: BriefingsBriefingIdRoute,
  BriefingsAllRoute: BriefingsAllRoute,
  ComponentsComponentNameRoute: ComponentsComponentNameRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  WatchlistTickerRoute: WatchlistTickerRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
